#!/bin/sh

lock() {
    i3-msg 'workspace number 1: www;'
    i3lock -c 111111
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        ~/.i3/shutdown
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        ~/.i3/shutdown
        systemctl reboot
        ;;
    shutdown)
        ~/.i3/shutdown
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
